SELECT
    V.[VEND_NOME]             AS NOME_VENDEDOR,
    P.[PROD_CODFABRIC]        AS COD_FABRICANTE,
    PO.[PEDOR_DATAALTERACAO]  AS DATA_ALTERACAO,
    PO.[PEDOR_RAZAOSOCIAL]    AS NOME_CLIENTE,
    PO.[ID_CODVENDEDOR]       AS COD_VENDEDOR,
    PR.[ID_NUMPEDORC]         AS NUM_PEDIDO,
    PR.[ID_CODPRODUTO]        AS COD_INTERNO,
    PR.[EST_QUANTIDADE]       AS QUANTIDADE_RESERVADA
FROM [EST_RESERVA_PED] PR
LEFT JOIN [PEDIDOORCAMENTO] PO ON PR.[ID_NUMPEDORC] = PO.[ID_NUMPEDORC]
INNER JOIN [VWITEM] P ON PR.[ID_CODPRODUTO] = P.[ID_CODPRODUTO]
LEFT JOIN [VENDEDORES] V ON PO.[ID_CODVENDEDOR] = V.[ID_CODVENDEDOR]
WHERE 1 = 1
-- Os filtros serão adicionados aqui pelo Node.js