SELECT
	NF.[NF_NUMDOCUM]                   AS NUM_NOTA,
	NF.[NF_NOMEENTIDADE]               AS RAZAO_SOCIAL,
	NF.[NF_DATAEMIS]                   AS DATA_EMISSAO,
	NF.[NF_PESOBRUTO]                  AS PESO_BRUTO,
	NF.[ID_CODVENDEDOR]                AS ID_VENDEDOR,
	NF.[ID_CODTRANSP]                  AS ID_TRANSPORTADORA,
	NF.[NF_QUANTMERCAD]                AS QUANTIDADE_MERCADORIA,
	NF.[NF_TOTPROD]                    AS VALOR_TOTAL,
	NF.[NF_UNIDFEDENTD]                AS UF,
	NF.[NF_CEPENTID]                   AS CEP,
	NF.[NF_CIDADEENTID]                AS CIDADE,
	NF.[NF_CGCCPFENTIDADE]             AS CNPJ,
	T.[TRAN_NOME]                      AS NOME_TRANSPORTADORA,
	V.[VEND_NOME]                      AS NOME_VENDEDOR
FROM [NOTAFISCAL]       NF
LEFT JOIN [TRANSPORTADORAS] T ON NF.[ID_CODTRANSP]   = T.[ID_CODTRANSP]
LEFT JOIN [VENDEDORES]      V ON NF.[ID_CODVENDEDOR] = V.[ID_CODVENDEDOR]
WHERE NF.[ID_CODFILIAIS] = 1