SELECT
	PEF.[PROD_CODFABRIC]            AS COD_FABRICANTE,
	PEF.[PROD_PESOBRUTO]            AS PESO_BRUTO,
	PRD.[PROD_ALTURA]               AS ALTURA,
	PRD.[PROD_LARGURA]              AS LARGURA,
	PRD.[PROD_COMPRIMENTO]          AS COMPRIMENTO,
	IPO.[ID_CODPRODUTO]             AS COD_INTERNO,
	IPO.[ITPEDOR_DESCRPROD]         AS DESCRICAO,
	IPO.[ITPEDOR_VLRUNIT]           AS PRECO,
	IPO.[ITPEDOR_QUANTID]           AS QUANTIDADE
FROM [ITENSPEDIDOORCAMENTO] IPO
LEFT JOIN [PRODUTOS_EMPRESASFILIAIS] PEF ON IPO.[ID_CODPRODUTO] = PEF.[ID_CODPRODUTO]
LEFT JOIN [PRODUTOS] PRD ON IPO.[ID_CODPRODUTO] = PRD.[ID_CODPRODUTO]
WHERE PEF.[ID_CODFILIAIS] = 1
-- Os filtros serão adicionados aqui pelo Node.js