SELECT
PEF.[PROD_CODFABRIC] COD_FABRICANTE, 
PEF.[PROD_PESOBRUTO] PESO_BRUTO,
PRD.[PROD_ALTURA] ALTURA, 
PRD.[PROD_LARGURA] LARGURA, 
PRD.[PROD_COMPRIMENTO] COMPRIMENTO, 
IPO.[ID_CODPRODUTO] COD_INTERNO,
IPO.[ITPEDOR_DESCRPROD] DESCRICAO,
IPO.[ITPEDOR_VLRUNIT] PRECO,
IPO.[ITPEDOR_QUANTID] QUANTIDADE
FROM [ITENSPEDIDOORCAMENTO] IPO
LEFT JOIN [PRODUTOS_EMPRESASFILIAIS] PEF ON IPO.[ID_CODPRODUTO] = PEF.[ID_CODPRODUTO]
LEFT JOIN [PRODUTOS] PRD ON IPO.[ID_CODPRODUTO] = PRD.[ID_CODPRODUTO]
WHERE PEF.[ID_CODFILIAIS] = 1
-- Os filtros serão adicionados aqui pelo Node.js