SELECT
PEF.[PROD_CODFABRIC], 
PEF.[PROD_PESOBRUTO],
PRD.[PROD_ALTURA], 
PRD.[PROD_LARGURA], 
PRD.[PROD_COMPRIMENTO], 
IPO.[ID_CODPRODUTO],
IPO.[ITPEDOR_DESCRPROD],
IPO.[ITPEDOR_VLRUNIT],
IPO.[ITPEDOR_QUANTID] 
FROM [ITENSPEDIDOORCAMENTO] IPO
LEFT JOIN [PRODUTOS_EMPRESASFILIAIS] PEF ON IPO.[ID_CODPRODUTO] = PEF.[ID_CODPRODUTO]
LEFT JOIN [PRODUTOS] PRD ON IPO.[ID_CODPRODUTO] = PRD.[ID_CODPRODUTO]
WHERE PEF.[ID_CODFILIAIS] = 1
-- Os filtros serão adicionados aqui pelo Node.js