SELECT
PO.[ID_NUMPEDORC] NUM_PEDIDO,
PO.[PEDOR_DATA] DATA_PEDIDO, 
PO.[ID_TRANSPORTADORA] ID_TRANSPORTADORA,
PO.[ID_CODENTIDADE] ID_CLIENTE,
PO.[PEDOR_VLRTOTAL] VALOR_TOTAL,
E.[ENTI_RAZAOSOCIAL] RAZAO_SOCIAL,
PO.[ID_CODVENDEDOR] ID_VENDEDOR,
PO.[PEDOR_TOTQUANT] QUANTIDADE_MERCADORIA,
PO.[PEDOR_SITUACAO] SITUACAO,
PO.[PEDOR_OBSERVACAO] OBSERVACAO,
T.[TRAN_NOME] NOME_TRANSPORTADORA,
V.[VEND_NOME] NOME_VENDEDOR,
E.[ENTI_CNPJCPF] CNPJ,
E.[ENTI_CEP] CEP
FROM [PEDIDOORCAMENTO] PO
LEFT JOIN [TRANSPORTADORAS] T ON PO.[ID_TRANSPORTADORA] = T.[ID_CODTRANSP]
LEFT JOIN [VENDEDORES] V ON PO.[ID_CODVENDEDOR] = V.[ID_CODVENDEDOR]
LEFT JOIN [ENTIDADES] E ON PO.[ID_CODENTIDADE] = E.[ID_CODENTIDADE]
WHERE PO.[ID_CODFILIAIS] = 1
-- Os filtros serão adicionados aqui pelo Node.js