USE [BDAMPLUS];
WITH Reservas AS (
    SELECT 
        [ID_CODPRODUTO], 
        SUM([EST_QUANTIDADE]) as QuantidadeReservada
    FROM [dbo].[EST_RESERVA_PED]
    GROUP BY [ID_CODPRODUTO]
)
SELECT
    P.[ID_CODPRODUTO] AS COD_INTERNO,
    P.[PROD_CODFABRIC] AS COD_FABRICANTE,
    P.[PROD_CODBARRA] AS COD_BARRAS,
    P.[PROD_ESTATUAL] AS QUANT_TOTAL,
    (P.[PROD_ESTATUAL] - ISNULL(R.QuantidadeReservada, 0)) AS ESTOQUE_DISPONIVEL,
    P.[PROD_DESCRCOMPLETA] AS DESCRICAO,
    PR.[PROD_ALTURA] AS ALTURA,
    PR.[PROD_LARGURA] AS LARGURA,
    PR.[PROD_COMPRIMENTO] AS COMPRIMENTO,
    PR.[PROD_PESOLIQUIDO] * 12 AS PESO_LIQ,
    PE.[PROD_PESOBRUTO] * 12 AS PESO_BR,
    PE.[PROD_PRECOVENDA] AS PRECO,
    PD.[PRDE_RUA] AS RUA,
    PD.[PRDE_FILEIRA] AS FILEIRA,
    PR.[DataAlteracao] AS DATA_ALTERACAO
FROM [vwITEM] P
LEFT JOIN [PRODUTOS_EMPRESASFILIAIS] PE ON P.[ID_CODPRODUTO] = PE.[ID_CODPRODUTO]
LEFT JOIN [PRODUTOS] PR ON P.[ID_CODPRODUTO] = PR.[ID_CODPRODUTO]
LEFT JOIN [PRODUTODEPOSITO] PD ON PD.[ID_CODPRODUTO] = P.[ID_CODPRODUTO] AND PD.[ID_DEPOSITOS] = 2
LEFT JOIN Reservas R ON P.[ID_CODPRODUTO] = R.[ID_CODPRODUTO]
WHERE 1=1
    AND P.[ID_DEPOSITOS] = 2
    -- Os filtros serão adicionados aqui pelo Node.js