USE [BDAMPLUS]
SELECT
PO.[ID_NUMPEDORC] NUM_PEDIDO,
PO.[PEDOR_DATA] DATA_PEDIDO, 
PO.[ID_TRANSPORTADORA] ID_TRANSPORTADORA,
PO.[ID_CODENTIDADE] ID_CLIENTE,
PO.[PEDOR_VLRTOTAL] VALOR_TOTAL,
E.[ENTI_RAZAOSOCIAL] RAZAO_SOCIAL,
PO.[ID_CODVENDEDOR] ID_VENDEDOR,
SUM(I.[ITPEDOR_QUANTID]) QUANTIDADE,
PO.[PEDOR_SITUACAO] SITUACAO,
CAST(PO.[PEDOR_OBSERVACAO] AS VARCHAR(MAX)) OBSERVACAO,
PO.[PEDOR_PESOBRUTO] PESO_BRUTO,
T.[TRAN_NOME] NOME_TRANSPORTADORA,
V.[VEND_NOME] NOME_VENDEDOR,
E.[ENTI_CNPJCPF] CNPJ,
E.[ENTI_CEP] CEP
FROM [PEDIDOORCAMENTO] PO
LEFT JOIN [TRANSPORTADORAS] T ON PO.[ID_TRANSPORTADORA] = T.[ID_CODTRANSP]
LEFT JOIN [VENDEDORES] V ON PO.[ID_CODVENDEDOR] = V.[ID_CODVENDEDOR]
LEFT JOIN [ENTIDADES] E ON PO.[ID_CODENTIDADE] = E.[ID_CODENTIDADE]
LEFT JOIN [ITENSPEDIDOORCAMENTO] I ON PO.[ID_NUMPEDORC] = I.[ID_NUMPEDORC]
WHERE PO.[ID_CODFILIAIS] = 1
-- Os filtros serão adicionados aqui pelo Node.js
GROUP BY
  PO.[ID_NUMPEDORC],
  PO.[PEDOR_DATA], 
  PO.[ID_TRANSPORTADORA],
  PO.[ID_CODENTIDADE],
  PO.[PEDOR_VLRTOTAL],
  E.[ENTI_RAZAOSOCIAL],
  PO.[ID_CODVENDEDOR],
  PO.[PEDOR_SITUACAO],
  CAST(PO.[PEDOR_OBSERVACAO] AS VARCHAR(MAX)),
  PO.[PEDOR_PESOBRUTO],
  T.[TRAN_NOME],
  V.[VEND_NOME],
  E.[ENTI_CNPJCPF],
  E.[ENTI_CEP]