USE [BDAMPLUS]
SELECT
PO.[PEDOR_VLRTOTAL] VALOR_TOTAL,
PO.[PEDOR_SITUACAO] SITUACAO
FROM [PEDIDOORCAMENTO] PO
LEFT JOIN [VENDEDORES] V ON PO.[ID_CODVENDEDOR] = V.[ID_CODVENDEDOR]
WHERE PO.[ID_CODFILIAIS] = 1
AND PO.[PEDOR_DATA] BETWEEN DATEFROMPARTS(YEAR(GETDATE()), MONTH(GETDATE()), 1) AND EOMONTH(GETDATE())
-- Os filtros serão adicionados aqui pelo Node.js
