SELECT
NF.[NF_NUMDOCUM] NUM_NOTA,
NF.[NF_NOMEENTIDADE] RAZAO_SOCIAL,
NF.[NF_DATAEMIS] DATA_EMISSAO,
NF.[NF_PESOBRUTO] PESO_BRUTO,
NF.[ID_CODVENDEDOR] ID_VENDEDOR,
NF.[ID_CODTRANSP] ID_TRANSPORTADORA,
NF.[NF_QUANTMERCAD] QUANTIDADE_MERCADORIA,
NF.[NF_TOTPROD] VALOR_TOTAL,
NF.[NF_UNIDFEDENTD] UF,
NF.[NF_CEPENTID] CEP,
NF.[NF_CIDADEENTID] CIDADE,
NF.[NF_CGCCPFENTIDADE] CNPJ,
T.[TRAN_NOME] NOME_TRANSPORTADORA,
V.[VEND_NOME] NOME_VENDEDOR
FROM [NOTAFISCAL] NF
LEFT JOIN [TRANSPORTADORAS] T ON NF.[ID_CODTRANSP] = T.[ID_CODTRANSP]
LEFT JOIN [VENDEDORES] V ON NF.[ID_CODVENDEDOR] = V.[ID_CODVENDEDOR]
WHERE NF.[ID_CODFILIAIS] = 1
-- Os filtros serão adicionados aqui pelo Node.js