USE [BDAMPLUS];
WITH GradeInfo AS (
    SELECT
        ID_GRADE_ECOMERCE,
        STRING_AGG(CONVERT(VARCHAR, [QUANTIDADE]), ',') AS QUANTIDADES,
        STRING_AGG(CONVERT(VARCHAR, [NUMERO]), ',') AS NUMEROS
    FROM [GRADE_TAMANHO_ECOMERCE]
    GROUP BY ID_GRADE_ECOMERCE
)
SELECT 
    P.[ID_CODPRODUTO] COD_INTERNO,
    P.[PROD_DESCRCOMPLETA] PROD_DESCRICAO,
    P.[PROD_CODFABRIC] COD_FABRICANTE,
    P.[ID_CODGRUPO] COD_GRUPO,
    P.[PROD_CODBARRA] COD_BARRAS,
    GI.[GRUP_DESCRICAO] AS GRUPO_DESCRICAO,
    PE.[DESCRICAO] AS ECOMMERCE_DESCRICAO,
    PE.[ID_CORES_ECOMERCE] AS COD_COR_ECOMMERCE,
    PE.[SKU_PRODUTO_PAI] AS PAI,
    PE.[ID_GRADE_ECOMERCE] AS COD_GRADE,
    CE.[DESCRICAO] AS COR_DESCRICAO,
    PR.[PROD_ALTURA] AS ALTURA,
    PR.[PROD_LARGURA] AS LARGURA,
    PR.[PROD_COMPRIMENTO] AS COMPRIMENTO,
    PR.[PROD_PESOLIQUIDO] AS PESO_LIQUIDO,
    PA.[PRO_ATIVO_ECOMMERCE] AS ATIVO_ECOMMERCE,
    PA.[PRO_INTEGRACAO_ECOMMERCE] AS INTEGRACAO_ECOMMERCE,
    PA.[ID_CODFILIAIS] AS COD_FILIAIS,
    PE.[CODIGO_COR] AS COD_COR,
    GInfo.QUANTIDADES,
    GInfo.NUMEROS
FROM [vwITEM] P
    LEFT JOIN [GrupoItens] GI ON P.ID_CODGRUPO = GI.ID_CODGRUPO
    LEFT JOIN [PRODUTOS_ECOMERCE] PE ON P.ID_CODPRODUTO = PE.ID_CODPRODUTO
    LEFT JOIN [CORES_ECOMERCE] CE ON PE.ID_CORES_ECOMERCE = CE.ID_CHAVE
    LEFT JOIN GradeInfo GInfo ON PE.ID_GRADE_ECOMERCE = GInfo.ID_GRADE_ECOMERCE
    LEFT JOIN [PRODUTOS_EMPRESASFILIAIS] PA ON P.ID_CODPRODUTO = PA.ID_CODPRODUTO
    LEFT JOIN [PRODUTOS] PR ON P.ID_CODPRODUTO = PR.ID_CODPRODUTO
WHERE 1 = 1
    AND PA.[ID_CODFILIAIS] = 1
    AND P.[ID_DEPOSITOS] = 2
    -- Os filtros serão adicionados aqui pelo Node.js